apiVersion: v1
kind: Pod
metadata:
  name: rockero-loco
  namespace: rock
  annotations:
    lider: "Laura"
    music-preference: "rock"
spec:
  containers:
    - name: rockero
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "guitarra-electrica"
      effect: "NoSchedule"
