apiVersion: v1
kind: Pod
metadata:
  name: reggaeton-beat-loco
  namespace: reggaeton
  annotations:
    lider: "Laura"
    student: "Oscar"
    music-preference: "reggaeton"
spec:
  containers:
    - name: flow-intenso
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "perreo-intenso"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - urbano