apiVersion: v1
kind: Pod
metadata:
  name: rockero-cdc-loco
  namespace: rock
  annotations:
    lider: "Laura"
    student: "Cristian"
    music-preference: "rock"
spec:
  containers:
    - name: aerosmith
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "guitarra-electrica"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - metalero