apiVersion: v1
kind: Pod
metadata:
  name: reggaeton-loco
  namespace: reggaeton
  annotations:
    lider: "Laura"
    studen: "Camilo"
    music-preference: "reggaeton"
spec:
  containers:
    - name: perreador
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "perreo-intenso"
      effect: "NoSchedule"